image: docker:latest
services:
  - docker:dind

stages:
  - build

frontend-build:
  stage: build
  only:
    - dev
    - main
  script:
    - cp $WEBAPP_UI_BUILD_FILE .conf.webapp-ui
    # Build the frontend
    - docker build -f Dockerfile $(for i in `cat .conf.webapp-ui`; do out="--build-arg $i $out" ; done; echo $out;out="") --build-arg BLOCKCHAIN_LIB_REGISTRY_DOMAIN=$BLOCKCHAIN_LIB_REGISTRY_DOMAIN --build-arg BLOCKCHAIN_LIB_REGISTRY_READ_TOKEN=$BLOCKCHAIN_LIB_REGISTRY_READ_TOKEN --build-arg COFFEE_TRADING_LIB_REGISTRY_DOMAIN=$COFFEE_TRADING_LIB_REGISTRY_DOMAIN --build-arg COFFEE_TRADING_LIB_REGISTRY_READ_TOKEN=$COFFEE_TRADING_LIB_REGISTRY_READ_TOKEN --build-arg UNECE_COTTON_FETCH_REGISTRY_READ_TOKEN=$UNECE_COTTON_FETCH_REGISTRY_READ_TOKEN --build-arg UNECE_COTTON_FETCH_REGISTRY_DOMAIN=$UNECE_COTTON_FETCH_REGISTRY_DOMAIN -t gitlab-core.supsi.ch:5050/dti-isin/giuliano.gremlich/blockchain/coffe-trading/kbc-platform .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push gitlab-core.supsi.ch:5050/dti-isin/giuliano.gremlich/blockchain/coffe-trading/kbc-platform
